name: mcq_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  cloud_firestore: ^4.15.1
  provider: ^6.1.2
  firebase_auth: ^4.19.1
  firebase_storage: ^11.6.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoMono-VariableFont_wght.ttf

  uses-material-design: true